name: Age-Gender Detection CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opencv-python-headless numpy flask
      shell: bash
      
    - name: Download face model
      run: |
        wget -O face_model.caffemodel http://example.com/path/to/faceModel.caffemodel
        wget -O face_proto.prototxt http://example.com/path/to/faceProto.prototxt
        
    - name: Run tests
      run: |
        python -m unittest test.py
      shell: bash
